apiVersion: v1
kind: ConfigMap
metadata:
  name: pve-exporter-config
  namespace: monitoring
data:
  pve.yml: |-
    default:
        user: ${PVE_USER}
        token_name: ${PVE_TOKEN_NAME}
        token_value: ${PVE_TOKEN_VALUE}
        verify_ssl: false