apiVersion: apps/v1
kind: Deployment
metadata:
  name: pve-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pve-exporter
  template:
    metadata:
      labels:
        app: pve-exporter
    spec:
      containers:
      - name: pve-exporter
        image: prompve/prometheus-pve-exporter
        ports:
        - containerPort: 9221
        volumeMounts:
        - name: config
          mountPath: /etc/prometheus/pve.yml
          subPath: pve.yml 
      volumes:
      - name: config
        configMap:
          name: pve-exporter-config
