- name: Add ingress-nginx Helm repo
  command: helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
  become: yes

- name: Update Helm repos
  command: helm repo update
  become: yes

- name: Install NGINX Ingress Controller
  command: >
    helm upgrade --install nginx-ingress ingress-nginx/ingress-nginx
    --create-namespace --namespace ingress-nginx
  become: yes

- name: Wait for Nginx Ingress controller to be ready
  command: >
    kubectl wait --namespace ingress-nginx
    --for=condition=ready pod
    -l app.kubernetes.io/component=controller
    --timeout=60s
  become: yes

- name: Set nginx ingress class as default
  command: >
    kubectl annotate ingressclass nginx
    ingressclass.kubernetes.io/is-default-class=true
    --overwrite