networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data:
    name: prometheus_data
  grafana_data:
    name: grafana_data

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:Z
    expose:
      - 9090
    networks:
      - monitoring
    depends_on:
      - node_exporter
      
  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    restart: unless-stopped
    networks:
      - monitoring

  pve-exporter:
    image: prompve/prometheus-pve-exporter
    container_name: pve-exporter
    ports:
      - '9221:9221'
    restart: unless-stopped
    volumes:
      - ./config/pve.yml:/etc/prometheus/pve.yml:Z
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - ./config/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml:Z  # Mounts the Grafana data source configuration file
      - ./config/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml:Z  # Mounts the Grafana dashboard configuration file
      - ./config/node_dashboard.json:/var/lib/grafana/dashboards/node_dashboard.json:Z
      - ./config/pve_dashboard.json:/var/lib/grafana/dashboards/pve_dashboard.json:Z
    restart: unless-stopped
    networks:
      - monitoring
    depends_on:
      - prometheus