networks:
  servarrnetwork:
    name: servarrnetwork
    ipam:
      config:
        - subnet: 172.18.0.0/24

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /mnt/DR01/media_server/docker/qbittorrent:/config
      - /mnt/DR01/media_server/data:/data
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    networks:
      servarrnetwork:
        ipv4_address: 172.18.0.10

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
    volumes:
      - /mnt/DR01/media_server/docker/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      servarrnetwork:
        ipv4_address: 172.18.0.11

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
    volumes:
      - /mnt/DR01/media_server/docker/sonarr:/config
      - /mnt/DR01/media_server/data:/data
    ports:
      - 8989:8989
    networks:
      servarrnetwork:
        ipv4_address: 172.18.0.12

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
    volumes:
      - /mnt/DR01/media_server/docker/radarr:/config
      - /mnt/DR01/media_server/data:/data
    ports:
      - 7878:7878
    networks:
      servarrnetwork:
        ipv4_address: 172.18.0.13

  lidarr:
    container_name: lidarr
    image: lscr.io/linuxserver/lidarr:latest
    restart: unless-stopped
    volumes:
      - /mnt/DR01/media_server/docker/lidarr:/config
      - /mnt/DR01/media_server/data:/data
    environment:
     - PUID=1000
     - PGID=1000
     - TZ=Europe/Bucharest
    ports:
      - 8686:8686
    networks:
      servarrnetwork:
        ipv4_address: 172.18.0.14

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
    volumes:
      - /mnt/DR01/media_server/docker/bazarr:/config
      - /mnt/DR01/media_server/data:/data
    ports:
      - 6767:6767
    networks:
      servarrnetwork:
        ipv4_address: 172.18.0.15

  jellyseerr:
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
    volumes:
      - /mnt/DR01/media_server/docker/jellyseerr:/app/config
    ports:
      - 5055:5055
    restart: unless-stopped
    networks:
      servarrnetwork:
        ipv4_address: 172.18.0.16
