---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install Python3, pip and venv
  apt:
    name:
      - python3
      - python3-pip
      - python3-venv
    state: present

- name: Ensure virtual environment directory exists
  file:
    path: /opt/ansible-venv
    state: directory
    mode: '0755'

- name: Create Python virtual environment
  command: python3 -m venv /opt/ansible-venv
  args:
    creates: /opt/ansible-venv/bin/activate

- name: Upgrade pip in virtual environment
  command: /opt/ansible-venv/bin/pip install --upgrade pip

- name: Install kubernetes and ansible in virtual environment
  command: /opt/ansible-venv/bin/pip install kubernetes ansible

- name: Install kubernetes.core collection in virtual environment
  command: /opt/ansible-venv/bin/ansible-galaxy collection install kubernetes.core
