- name: Create cert-manager namespace
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: cert-manager
    state: present

- name: Add Jetstack Helm repo
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io
    state: present

- name: Update Helm repos
  command: helm repo update

- name: Install cert-manager with CRDs
  kubernetes.core.helm:
    release_name: cert-manager
    chart_ref: jetstack/cert-manager
    namespace: cert-manager
    create_namespace: true
    release_values:
      installCRDs: true
    state: present
