- name: Install NFS server packages
  package:
    name: nfs-kernel-server
    state: present

- name: Create NFS export directory
  file:
    path: /srv/grafana-dashboards
    state: directory
    owner: 472        # UID Grafana
    group: 472        # GID Grafana
    mode: '0777'
    recurse: yes

- name: Configure NFS exports
  lineinfile:
    path: /etc/exports
    line: "/srv/grafana-dashboards *(rw,sync,no_root_squash)"
    create: yes
    state: present

- name: Export NFS shares
  command: exportfs -rav

- name: Ensure NFS server is running
  service:
    name: nfs-kernel-server
    state: started
    enabled: yes
