---
- name: Apply common configuration to all nodes
  hosts: all
  gather_facts: no
  become: yes
  roles:
    - common

- name: Prepare VM for Kubernetes tasks
  hosts: k3s_master
  gather_facts: no
  become: yes
  roles:
    - install-k8s-deps

- name: Setup K3s master
  hosts: k3s_master
  become: yes
  roles:
    - k3s-master

- name: Setup K3s worker
  hosts: k3s_worker
  become: yes
  roles:
    - k3s-worker

- name: Install Helm on master
  hosts: k3s_master
  become: yes
  roles:
    - helm

- name: Install NGINX Ingress on master
  hosts: k3s_master
  become: yes
  roles:
    - nginx-ingress

- name: Deploy k3s manifests
  hosts: k3s_master
  become: yes
  roles:
    - k3s-manifests-media

- name: Deploy grafana-dashboards to all nodes
  hosts: k3s_master, k3s_worker
  become: yes
  roles:
    - grafana-dashboards

- name: Deploy Monitoring
  hosts: k3s_master
  become: yes
  vars_files:
    - ../group_vars/all.yaml
  vars:
    ansible_python_interpreter: /opt/ansible-venv/bin/python
  roles:
    - k3s-manifests-monitoring