---
- name: Apply common configuration to all nodes
  hosts: all
  become: yes
  roles:
    - common

- name: Setup K3s master
  hosts: k3s_master
  become: yes
  roles:
    - k3s-master

- name: Setup K3s worker
  hosts: k3s_worker
  become: yes
  roles:
    - k3s-worker

- name: Install Helm on master
  hosts: k3s_master
  become: yes
  roles:
    - helm

- name: Install NGINX Ingress on master
  hosts: k3s_master
  become: yes
  roles:
    - nginx-ingress

- name: Deploy k3s manifests
  hosts: k3s_master
  become: yes
  roles:
    - k3s-manifests-media

- name: Deploy PVE exporter Secret
  hosts: k3s_master
  become: yes
  roles:
    - pve-exporter-secret
