apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      initContainers:
      - name: copy-dashboards
        image: busybox
        command: ["sh", "-c", "cp -r /source-dashboards/* /var/lib/grafana/dashboards/"]
        volumeMounts:
        - name: dashboards
          mountPath: /var/lib/grafana/dashboards
        - name: source-dashboards
          mountPath: /source-dashboards
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_USER
          value: admin
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: admin
        volumeMounts:
        - name: dashboards
          mountPath: /var/lib/grafana/dashboards
        - name: grafana-dashboards-config
          mountPath: /etc/grafana/provisioning/dashboards
        - name: grafana-datasources
          mountPath: /etc/grafana/provisioning/datasources
      volumes:
      - name: dashboards
        persistentVolumeClaim:
          claimName: grafana-dashboards-pvc
      - name: source-dashboards
        hostPath:
          path: /opt/grafana-dashboards
          type: Directory
      - name: grafana-dashboards-config
        configMap:
          name: grafana-dashboards-config
      - name: grafana-datasources
        configMap:
          name: grafana-datasources