apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-dashboards-pv
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ nfs_server }}
    path: /srv/grafana-dashboards
  persistentVolumeReclaimPolicy: Retain
